<?php

declare(strict_types=1);

/*
 * PaginationTesterLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PaginationTesterLib\Tests;

use Core\Types\CallbackCatcher;
use PaginationTesterLib\PaginationTesterClient;
use PaginationTesterLib\PaginationTesterClientBuilder;

class ClientFactory
{
    public static function create(CallbackCatcher $httpCallback): PaginationTesterClient
    {
        $clientBuilder = PaginationTesterClientBuilder::init();
        $clientBuilder = self::addConfigurationFromEnvironment($clientBuilder);
        $clientBuilder = self::addTestConfiguration($clientBuilder);
        return $clientBuilder->httpCallback($httpCallback)->build();
    }

    public static function addTestConfiguration(PaginationTesterClientBuilder $builder): PaginationTesterClientBuilder
    {
        return $builder;
    }

    public static function addConfigurationFromEnvironment(
        PaginationTesterClientBuilder $builder
    ): PaginationTesterClientBuilder {
        $timeout = getenv('PAGINATION_TESTER_LIB_TIMEOUT');
        $numberOfRetries = getenv('PAGINATION_TESTER_LIB_NUMBER_OF_RETRIES');
        $maximumRetryWaitTime = getenv('PAGINATION_TESTER_LIB_MAXIMUM_RETRY_WAIT_TIME');
        $environment = getenv('PAGINATION_TESTER_LIB_ENVIRONMENT');

        if (!empty($timeout) && \is_numeric($timeout)) {
            $builder->timeout(intval($timeout));
        }

        if (!empty($numberOfRetries) && \is_numeric($numberOfRetries)) {
            $builder->numberOfRetries(intval($numberOfRetries));
        }

        if (!empty($maximumRetryWaitTime) && \is_numeric($maximumRetryWaitTime)) {
            $builder->maximumRetryWaitTime(intval($maximumRetryWaitTime));
        }

        if (!empty($environment)) {
            $builder->environment($environment);
        }

        return $builder;
    }
}
