<?php

declare(strict_types=1);

/*
 * PaginationTesterLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PaginationTesterLib\Models\Builders;

use Core\Utils\CoreHelper;
use PaginationTesterLib\Models\Links;
use PaginationTesterLib\Models\Transaction;
use PaginationTesterLib\Models\TransactionsLinked;

/**
 * Builder for model TransactionsLinked
 *
 * @see TransactionsLinked
 */
class TransactionsLinkedBuilder
{
    /**
     * @var TransactionsLinked
     */
    private $instance;

    private function __construct(TransactionsLinked $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Transactions Linked Builder object.
     */
    public static function init(): self
    {
        return new self(new TransactionsLinked());
    }

    /**
     * Sets data field.
     *
     * @param Transaction[]|null $value
     */
    public function data(?array $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Sets links field.
     *
     * @param Links|null $value
     */
    public function links(?Links $value): self
    {
        $this->instance->setLinks($value);
        return $this;
    }

    /**
     * Initializes a new Transactions Linked object.
     */
    public function build(): TransactionsLinked
    {
        return CoreHelper::clone($this->instance);
    }
}
