<?php

declare(strict_types=1);

/*
 * PaginationTesterLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PaginationTesterLib\Models\Builders;

use Core\Utils\CoreHelper;
use PaginationTesterLib\Models\Transaction;
use PaginationTesterLib\Models\TransactionsOffset;

/**
 * Builder for model TransactionsOffset
 *
 * @see TransactionsOffset
 */
class TransactionsOffsetBuilder
{
    /**
     * @var TransactionsOffset
     */
    private $instance;

    private function __construct(TransactionsOffset $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Transactions Offset Builder object.
     */
    public static function init(): self
    {
        return new self(new TransactionsOffset());
    }

    /**
     * Sets data field.
     *
     * @param Transaction[]|null $value
     */
    public function data(?array $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Initializes a new Transactions Offset object.
     */
    public function build(): TransactionsOffset
    {
        return CoreHelper::clone($this->instance);
    }
}
